---
grails:
    profile: react
    codegen:
        defaultPackage: flug
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    cassandra:
        contactPoints: localhost
        port: 9042
        dbCreate: recreate-drop-unused
        stateless: false
        keyspace:
            name: flug #the name of the keyspace to use, default: the name of the application
            action: create #whether to create a keyspace, default: no keyspace created
            # keyspace properties to set only if the plugin is to create the keyspace
            durableWrites: true #default: false
            replicationStrategy: SIMPLE_STRATEGY # OR  NETWORK_TOPOLOGY_STRATEGY default: "SIMPLE_STRATEGY"
            replicationFactor: 1 #default: 1

---
grails:
    cors:
        enabled: true
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


environments:
    development:

    test:

    production:


